### ISSUE TITLE
EP preprocessing, cannot reproduce

### ISSUE THREAD

**Issue by terarachang** [nyu-mll/jiant-v1-legacy#1119]
Hi,
I followed the requirements of packages and ran get_and_process_all_data.sh for the edge probing tasks in OntoNotes.
I can successfully generate the preprocessed data(e.g. const/pos, const/nonterminal,  coref/,  ner/,  srl/),
but I noticed that for some tasks, running the same script twice generated different .json files.
I wonder if it's normal. And if it is, where does the randomness come from?

Thanks!

**Comment by sleepinyourhat** [comment]
We only have limited support bandwidth for v1, but if anyone would know, it'd probably be @iftenney.

**Comment by iftenney** [comment]
That's odd, there shouldn't be any randomness in the preprocessing. Could you post some of the diffs?

**Comment by terarachang** [comment]
I just realized that the differences in srl and ner are caused by the orders of the dict.
After adding export PYTHONHASHSEED=0 in get_and_process_all_data.sh, I can reproduce the results of two runs now.

Thanks!
